# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c8a23e51e5e33ed15af8ec55b25811fd494e9ea0ee3421f53c27d86d289cf31f374740f00f92ee12b2e4c37d9bb792f7d4cdb92f43eb34d58c8a412350209865

test:
  secret_key_base: b3ce1cd685fbb2ddec60d3cdd0ae6c4224be85dde856f5663387d17cc78af5b38f38b5e0ba0d3025eef446f8b01badc8ecea443d0f7a94539fdb60ec25de6fbc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
